services:
  app:
    container_name: streamlit-eda
    build:
      context: .
    ports: ["8501:8501"]
    environment:
      SUPABASE_URL: ${SUPABASE_URL:-""}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:-""}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-""}
